package app

import (
	"fmt"
	"os"
	"sort"
	"strings"
	"time"
)

// LockfileEntry represents one resolved package in the lockfile
type LockfileEntry struct {
	Name    string
	Version string
}

// GenerateLockfile writes a deterministic lockfile from a resolution result
func GenerateLockfile(result SolverResult, outputPath string) error {
	entries := make([]LockfileEntry, 0, len(result.Resolved))
	for name, ver := range result.Resolved {
		entries = append(entries, LockfileEntry{
			Name:    name,
			Version: ver.Raw,
		})
	}

	// Sort for determinism
	sort.Slice(entries, func(i, j int) bool {
		return strings.ToLower(entries[i].Name) < strings.ToLower(entries[j].Name)
	})

	var sb strings.Builder
	sb.WriteString("# depsolver.lock\n")
	sb.WriteString(fmt.Sprintf("# Generated: %s\n", time.Now().UTC().Format(time.RFC3339)))
	sb.WriteString("# This file is automatically generated. Do not edit manually.\n")
	sb.WriteString("#\n")
	sb.WriteString("# Format: package==version\n")
	sb.WriteString("\n")
	for _, e := range entries {
		sb.WriteString(fmt.Sprintf("%s==%s\n", e.Name, e.Version))
	}

	return os.WriteFile(outputPath, []byte(sb.String()), 0644)
}

// PrintLockfile prints the lockfile contents to stdout
func PrintLockfile(result SolverResult) {
	entries := make([]LockfileEntry, 0, len(result.Resolved))
	for name, ver := range result.Resolved {
		entries = append(entries, LockfileEntry{Name: name, Version: ver.Raw})
	}
	sort.Slice(entries, func(i, j int) bool {
		return strings.ToLower(entries[i].Name) < strings.ToLower(entries[j].Name)
	})

	fmt.Println()
	fmt.Println("╔══════════════════════════════════════════════╗")
	fmt.Println("║              depsolver.lock                  ║")
	fmt.Println("╚══════════════════════════════════════════════╝")
	for _, e := range entries {
		fmt.Printf("%s==%s\n", e.Name, e.Version)
	}
}
