package docker

import (
	"fmt"
	"os"
	"path/filepath"

	"github.com/devyani1512/DependencyResolver/internal/scanner"
	"github.com/devyani1512/DependencyResolver/internal/services"
)

// GenerateAppDockerfile creates Dockerfile for the application
func GenerateAppDockerfile(info *scanner.ProjectInfo) error {
	var dockerfile string

	switch info.Type {
	case "python":
		dockerfile = generatePythonDockerfile(info)
	case "node":
		dockerfile = generateNodeDockerfile(info)
	default:
		return fmt.Errorf("unsupported project type: %s", info.Type)
	}

	dockerfilePath := filepath.Join(info.Path, "Dockerfile")
	return os.WriteFile(dockerfilePath, []byte(dockerfile), 0644)
}

func generatePythonDockerfile(info *scanner.ProjectInfo) string {
	return `# Auto-generated by DependencyResolver
FROM python:3.11-slim

WORKDIR /app

# Install system dependencies
RUN apt-get update && apt-get install -y \
    gcc \
    postgresql-client \
    && rm -rf /var/lib/apt/lists/*

# Copy requirements and install Python dependencies
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy application code
COPY . .

# Expose port
EXPOSE 8000

# Run the application
CMD ["python", "app.py"]
`
}

func generateNodeDockerfile(info *scanner.ProjectInfo) string {
	return `# Auto-generated by DependencyResolver
FROM node:18-alpine

WORKDIR /app

# Copy package files
COPY package*.json ./

# Install dependencies
RUN npm ci --only=production

# Copy application code
COPY . .

# Expose port
EXPOSE 3000

# Run the application
CMD ["npm", "start"]
`
}

// GenerateFullDockerCompose creates docker-compose with app + services
func GenerateFullDockerCompose(info *scanner.ProjectInfo, serviceConfigs []services.ServiceConfig) error {
	yaml := `version: '3.8'

services:
  app:
    build: .
    ports:
`

	// Determine port based on project type
	port := "8000"
	if info.Type == "node" {
		port = "3000"
	}
	yaml += fmt.Sprintf("      - \"%s:%s\"\n", port, port)

	// Add service dependencies
	if len(serviceConfigs) > 0 {
		yaml += "    depends_on:\n"
		for _, svc := range serviceConfigs {
			yaml += fmt.Sprintf("      - %s\n", svc.Name)
		}
		yaml += "    environment:\n"
		// Add connection strings
		for _, svc := range serviceConfigs {
			if svc.Name == "postgres" {
				yaml += "      DATABASE_URL: postgresql://dev:devpass@postgres:5432/devdb\n"
			}
			if svc.Name == "redis" {
				yaml += "      REDIS_URL: redis://redis:6379\n"
			}
		}
	}

	yaml += "\n"

	// Add service definitions
	for _, svc := range serviceConfigs {
		yaml += fmt.Sprintf("  %s:\n", svc.Name)
		yaml += fmt.Sprintf("    image: %s\n", svc.Image)
		yaml += fmt.Sprintf("    ports:\n")
		yaml += fmt.Sprintf("      - \"%d:%d\"\n", svc.Port, svc.Port)

		if len(svc.Environment) > 0 {
			yaml += "    environment:\n"
			for key, val := range svc.Environment {
				yaml += fmt.Sprintf("      %s: %s\n", key, val)
			}
		}
		yaml += "\n"
	}

	composeFile := filepath.Join(info.Path, "docker-compose.yml")
	return os.WriteFile(composeFile, []byte(yaml), 0644)
}
